name: 'remote debug action'
description: 'ssh to remote or publish port to internet'
inputs:
  ngrok_token:
    required: true
    description: ngrok auth token
  user_passwd:
    required: false
    default: remoteAction
    description: 'set ssh password what you want'
  forward_port:
    required: false
    default: 22
    description: 'forward tcp port'
  time_limit:
    required: false
    default: 600
    description: 'service time limit'
outputs:
  context:
    description: 'ssh link address or just publish'
runs:
  using: 'node12'
  main: 'dist/index.js'
