name: 'remote action'
description: 'ssh to remote or publish port to internet'
inputs:
  ngrok_token:
    required: true
    description: ngrok auth token
  ngrok_type:
    required: false
    default: 'ssh'
    description: 'ssh publish'
  user_passwd:
    required: false
    description: 'set ssh password'
outputs:
  context:
    description: 'ssh link address or just publish'
runs:
  using: 'node12'
  main: 'index.js'
