name: debugger-action
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start SSH via Ngrok
        uses: elanworld/debug-action@master
      - name: Setup Debug Session
        if: ${{ failure() }}
        uses: csexton/debugger-action@master